In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('kidney_disease.csv')

In [31]:
df.shape

(400, 26)

In [32]:
df.info()  #there is null values in the dataset, we need to handle them before training the model.

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    str
 17  wc              295 non-null    str
 18  rc              270 non-null    str
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(11), int64(1), str(14)
memory usage: 81.4 KB

In [33]:
df.head() #inputs datas are age, blood pressure, specific gravity, albumin, sugar, red blood cells, pus cell, pus cell clumps, bacteria, blood glucose random, blood urea, serum creatinine, sodium, potassium, hemoglobin, packed cell volume, white blood cell count, red blood cell count and hypertension.
          # The target variable is class which has two values: 'ckd' and 'notckd'

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

Here we don't need id column. It is unnecessary data and not useful for our model, so we will drop it.

In [34]:
df.drop('id', axis = 1, inplace = True) #the id column is not useful for our model, so we will drop it.

In [35]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

Data handling.1

changing the columns names because they are not user friendly

In [36]:
#changing the columns names because they are not user friendly
df.columns = ['age', 'blood_pressure','specific_gravity', 'albumin', 'sugar', 'red_blood_cells', 
              'pus_cell', 'pus_cell_clumps', 'bacteria', 'blood_glucose_random', 'blood_urea', 
              'serum_creatinine', 'sodium', 'potassium', 'hemoglobin', 'packed_cell_volume', 
              'white_blood_cell_count', 'red_blood_cell_count', 'hypertension', 'diabetes_mellitus',
              'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia','class']

In [37]:
df.head()

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

Data handling.2

In the above datas, packed_cell_volume, white_blood_cell_count, red_blood_cell_count are in text datatype, we have to convert these into numeric type

In [38]:
text_columns = ['packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count']
for i in text_columns:
    print(f"{i}: {df[i].dtype}")

packed_cell_volume: str
white_blood_cell_count: str
red_blood_cell_count: str

now convert the data type in to numaric (i.e., float)

In [39]:
def convert_text_to_numeric(df, column):
    df[column] = pd.to_numeric(df[column], errors='coerce')
    
for column in text_columns:
    convert_text_to_numeric(df, column)
    print(f"{column}: {df[column].dtype}")

packed_cell_volume: float64
white_blood_cell_count: float64
red_blood_cell_count: float64

Data handling.3

handling missing values

In [40]:
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False).head(20)

red_blood_cells           152
red_blood_cell_count      131
white_blood_cell_count    106
potassium                  88
sodium                     87
packed_cell_volume         71
pus_cell                   65
hemoglobin                 52
sugar                      49
specific_gravity           47
albumin                    46
blood_glucose_random       44
blood_urea                 19
serum_creatinine           17
blood_pressure             12
age                         9
pus_cell_clumps             4
bacteria                    4
hypertension                2
diabetes_mellitus           2
dtype: int64

In [41]:
df.columns

Index(['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar',
       'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria',
       'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium',
       'potassium', 'hemoglobin', 'packed_cell_volume',
       'white_blood_cell_count', 'red_blood_cell_count', 'hypertension',
       'diabetes_mellitus', 'coronary_artery_disease', 'appetite',
       'pedal_edema', 'anemia', 'class'],
      dtype='str')

data frames contain numeric as well as category columns

so we need to fill the column which contains numeric data with average and fill the column which contains category data with mode(frequent data)

In [42]:
# Separate columns
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

# Fill numeric columns with mean
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].mean())

# Fill categorical columns with mode
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

C:\Users\mahes\AppData\Local\Temp\ipykernel_20852\1612962733.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

In [43]:
#now null values are handled
df.isnull().sum()

age                        0
blood_pressure             0
specific_gravity           0
albumin                    0
sugar                      0
red_blood_cells            0
pus_cell                   0
pus_cell_clumps            0
bacteria                   0
blood_glucose_random       0
blood_urea                 0
serum_creatinine           0
sodium                     0
potassium                  0
hemoglobin                 0
packed_cell_volume         0
white_blood_cell_count     0
red_blood_cell_count       0
hypertension               0
diabetes_mellitus          0
coronary_artery_disease    0
appetite                   0
pedal_edema                0
anemia                     0
class                      0
dtype: int64

Find unique values and replace

In [44]:
# Check unique values in categorical columns

print(f"diabetes_mellitus:- {df['diabetes_mellitus'].unique()}")
print(f"coronary_artery_disease:- {df['coronary_artery_disease'].unique()}")
print(f"class:- {df['class'].unique()} ")

diabetes_mellitus:- <StringArray>
['yes', 'no', ' yes', '\tno', '\tyes']
Length: 5, dtype: str
coronary_artery_disease:- <StringArray>
['no', 'yes', '\tno']
Length: 3, dtype: str
class:- <StringArray>
['ckd', 'ckd\t', 'notckd']
Length: 3, dtype: str

In [45]:
df['diabetes_mellitus'] = df['diabetes_mellitus'].replace({' yes': 'yes', '\tno': 'no', '\tyes': 'yes'})
df['coronary_artery_disease'] = df['coronary_artery_disease'].replace({'\tno': 'no'})
df['class'] = df['class'].replace({'ckd\t': 'ckd', 'notckd': 'not ckd'})

In [46]:
#now again check unique values in categorical columns
print(f"diabetes_mellitus:- {df['diabetes_mellitus'].unique()}")
print(f"coronary_artery_disease:- {df['coronary_artery_disease'].unique()}")
print(f"class:- {df['class'].unique()} ")

diabetes_mellitus:- <StringArray>
['yes', 'no']
Length: 2, dtype: str
coronary_artery_disease:- <StringArray>
['no', 'yes']
Length: 2, dtype: str
class:- <StringArray>
['ckd', 'not ckd']
Length: 2, dtype: str

FEATURE ENCODING

feature encoding - It means change the categorical values to numerical values because machine understand only numerical datas

By simple method is mapping because only their is 2types of catogory(i.e, yes, no and ckd, not ckd)

In [47]:
df['class'] = df['class'].map({'ckd': 1, 'not ckd': 0})
df['red_blood_cells'] = df['red_blood_cells'].map({'normal': 0, 'abnormal': 1})
df['pus_cell'] = df['pus_cell'].map({'normal': 0, 'abnormal': 1})
df['pus_cell_clumps'] = df['pus_cell_clumps'].map({'notpresent  ': 0, 'present': 1})
df['bacteria'] = df['bacteria'].map({'notpresent  ': 0, 'present': 1})
df['hypertension'] = df['hypertension'].map({'no': 0, 'yes': 1})
df['diabetes_mellitus'] = df['diabetes_mellitus'].map({'no': 0, 'yes': 1})
df['coronary_artery_disease'] = df['coronary_artery_disease'].map({'no': 0, 'yes': 1})
df['appetite'] = df['appetite'].map({'good': 1, 'poor': 0})
df['pedal_edema'] = df['pedal_edema'].map({'no': 0, 'yes': 1})
df['anemia'] = df['anemia'].map({'no': 0, 'yes': 1})

In [48]:
df.head()

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,0,0,NaN,NaN,121.000000,...,44.0,7800.0,5.200000,1,1,0,1,0,0,1
1,7.0,50.0,1.020,4.0,0.0,0,0,NaN,NaN,148.036517,...,38.0,6000.0,4.707435,0,0,0,1,0,0,1
2,62.0,80.0,1.010,2.0,3.0,0,0,NaN,NaN,423.000000,...,31.0,7500.0,4.707435,0,1,0,0,0,1,1
3,48.0,70.0,1.005,4.0,0.0,0,1,1.0,NaN,117.000000,...,32.0,6700.0,3.900000,1,0,0,0,1,1,1
4,51.0,80.0,1.010,2.0,0.0,0,0,NaN,NaN,106.000000,...,35.0,7300.0,4.600000,0,0,0,1,0,0,1

CORELATION

It means how one column and other columns are related

In [51]:
import matplotlib.pyplot as plt